# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://ajinkyabapat.me
baseurl: /
title: Ajinkya Bapat
author: Ajinkya Bapat
description: Personal blog and resume
avatar: profile.jpg
email: ajinkyabapat12@gmail.com
github: AjinkyaBapat # username
twitter: ajinkyab12
linkedin: ajinkyabapat
facebook: iamajinkyabapat
instagram: ajinkyab12
stackoverflow: users/6202024/ajinkya-bapat   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
disqus: ajinkyabapat-me
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
